on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04-arm
    name: Test
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: hurelhuyag/flutter-arm64-action@HEAD
        with:
          channel: 'stable'

      - run: flutter test
